name: Trigger auto deployment for ca-user-workload

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-user-workload-AutoDeployTrigger-8d4f4d9c-283f-4d22-9615-3d981eccedad.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CAUSERWORKLOAD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAUSERWORKLOAD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAUSERWORKLOAD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.CAUSERWORKLOAD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAUSERWORKLOAD_REGISTRY_PASSWORD }}
          containerAppName: ca-user-workload
          resourceGroup: rg-user-workload
          imageToBuild: jitangupta/ca-user-workload:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


